config/routes.rb
Rails.application.routes.draw do

  #
  # API
  #

  namespace :api, defaults: { format: :json } do
    get 'status' => 'status#index'

    scope ':key' do
      get 'status' => 'status#index'

      resources :journeys, only: [:create, :update, :destroy]

      get 'conditions' => 'structures#conditions'
      get 'actions'    => 'structures#actions'
      get 'all'        => 'structures#all'
    end
  end

  #
  # Admin
  #

  namespace :admin do
    get '', to: 'home#index', as: :home

    resources :api_keys
    resources :journeys
    resources :structures do
      get :tree, on: :collection
    end
    resources :users
  end

  #
  # Devise
  #

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
  end

  #
  # Application
  #
  get 'j/:token',   to: 'home#share',  as: :share
  get 'conditions', to: 'home#conditions', as: :conditions
  get 'actions',    to: 'home#actions', as: :actions
  get 'save',       to: 'home#save', as: :save
  get 'journeys',   to: 'home#journeys', as: :journeys
  get 'raw',        to: 'home#raw', as: :raw

  resources :journeys, only: [:index, :show, :destroy]

  #
  # Defaults
  #

  root to: "home#index"
end

app/models/journey.rb
class Journey < ApplicationRecord

  #
  # Validations
  #

  validates :name, presence: true
  validates :data, presence: true

  #
  # Associations
  #

  belongs_to :user

  #
  # Generators
  #

  after_initialize :check_token

  def check_token
    self.token = SecureRandom.uuid unless token.present?
  end

end

app/controllers/admin/journeys_controller.rb
class Admin::JourneysController < AdminController
  before_action :set_journey, only: [:show, :edit, :update, :destroy]

  def index
    @journeys = Journey.all
  end

  def show
  end

  def new
    @journey = Journey.new
  end

  def edit
  end

  def create
    @journey = Journey.new(journey_params)

    respond_to do |format|
      if @journey.save
        format.html { redirect_to [:admin, @journey], notice: 'Journey was successfully created.' }
        format.json { render :show, status: :created, location: @journey }
      else
        format.html { render :new }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @journey.update(journey_params)
        format.html { redirect_to [:admin, @journey], notice: 'Journey was successfully updated.' }
        format.json { render :show, status: :ok, location: @journey }
      else
        format.html { render :edit }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @journey.destroy
    respond_to do |format|
      format.html { redirect_to admin_journeys_url, notice: 'Journey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_journey
    @journey = Journey.find(params[:id])
  end

  def journey_params
    params.require(:journey).permit(:user_id, :name, :data)
  end
end

app/controllers/api/journeys_controller.rb
class Api::JourneysController < ApiController

  def create
    @journey = @user.journeys.create(journey_params)
    render :show
  end

  def update
    @journey = @user.journeys.find(params[:id])
    @journey.update(journey_params)
    render :show
  end

  def destroy
    @journey = @user.journeys.find(params[:id])
    @journey.destroy
    render :show
  end

private

  def journey_params
    params.require(:journey).permit(:user_id, :name, data: {})
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location
  before_action :set_journey, only: [:show, :destroy]

  def index
    @journeys = current_user.journeys
  end

  def show
  end

  def destroy
    @journey.destroy
    redirect_to journeys_path
  end

private
  def set_location
    @location = :journeys
  end

  def set_journey
    @journey = current_user.journeys.find_by(token: params[:id])
  end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/admin/journeys/_form.html.haml
= form_for [:admin, @journey] do |f|
  - if @journey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@journey.errors.count, "error")} prohibited this journey from being saved:"
      %ul
        - @journey.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :user_id
    = f.collection_select :user_id, User.order(:email), :id, :email, {include_blank: true}, { class: 'form-control' }
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :data
    = f.text_field :data, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/journeys/edit.html.haml
%h1 Editing journey

= render 'form'

= link_to 'Show', [:admin, @journey]
\|
= link_to 'Back', admin_journeys_path

app/views/admin/journeys/index.html.haml
%table.datatables
  %thead
    %tr
      %th User
      %th Name
      %th Data
      %th Created
      %th Token
      %th

  %tbody
    - @journeys.each do |journey|
      %tr
        %td= journey.user.display_name
        %td= journey.name
        %td= journey.data
        %td= journey.created_at
        %td= journey.token
        %td
          = link_to 'Show', [:admin, journey]
          = link_to 'Edit', edit_admin_journey_path(journey)
          = link_to 'Destroy', [:admin, journey], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Journey', new_admin_journey_path

app/views/admin/journeys/new.html.haml
%h1 New journey

= render 'form'

= link_to 'Back', admin_journeys_path

app/views/admin/journeys/show.html.haml
%p#notice= notice

%p
  %b User:
  = @journey.user_id
%p
  %b Name:
  = @journey.name
%p
  %b Data:
  %pre= JSON.pretty_generate(JSON.parse(@journey.data), {indent: "  ", object_nl: "\n"})
%p
  %b Token:
  = link_to journey_path(@journey.token)

= link_to 'Edit', edit_admin_journey_path(@journey)
\|
= link_to 'Back', admin_journeys_path