config/routes.rb
Rails.application.routes.draw do

  #
  # API
  #

  namespace :api, defaults: { format: :json } do
    get 'status' => 'status#index'

    scope ':key' do
      get 'status' => 'status#index'

      resources :journeys, only: [:create, :update, :destroy]

      get 'conditions' => 'structures#conditions'
      get 'actions'    => 'structures#actions'
      get 'all'        => 'structures#all'
    end
  end

  #
  # Admin
  #

  namespace :admin do
    get '', to: 'home#index', as: :home

    resources :api_keys
    resources :journeys
    resources :structures do
      get :tree, on: :collection
    end
    resources :users
  end

  #
  # Devise
  #

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
  end

  #
  # Application
  #
  get 'j/:token',   to: 'home#share',  as: :share
  get 'conditions', to: 'home#conditions', as: :conditions
  get 'actions',    to: 'home#actions', as: :actions
  get 'save',       to: 'home#save', as: :save
  get 'journeys',   to: 'home#journeys', as: :journeys
  get 'raw',        to: 'home#raw', as: :raw

  resources :journeys, only: [:index, :show, :destroy]

  #
  # Defaults
  #

  root to: "home#index"
end

app/models/structure.rb
class Structure < ApplicationRecord
  acts_as_nested_set order_column: "name", counter_cache: :children_count

  #
  # Validations
  #

  validates :name, presence: true
  validates :flavor, presence: true
  validates :handle, presence: true, uniqueness: true

  #
  # Callbacks
  #

  before_save :format_data
  before_validation :build_handle

  def display_flavor
    case self.flavor
    when 'condition_group'
      'Group'
    when 'action'
      'Action'
    else
      self.flavor.try(:capitalize) || '?Flavor?'
    end
  end

  def flavor_letter()
    display_flavor()[0].downcase
  end

  def format_data()
    begin
      # self.data = eval(self.data).to_json if self.data.is_a?(String) # DANGER!!!!
      self.data = JSON.parse(self.data) if self.data.is_a?(String)
    rescue => e
      self.errors.add(:data, e.message)
    end
  end

  def data_hash()
    begin
      if self.data.is_a?(String)
        JSON.parse(self.data)
      else
        self.data
      end
    rescue => e
      self.errors.add(:data, e.message)
    end
  end

  def gen_handle()
    par_nm   = ((self.parent && self.parent.flavor_letter!='g' && (self.parent.name[0..3]+'_')) || '')
    gran_nm  = ((self.parent && self.parent && self.parent.parent && self.parent.parent.flavor_letter!='g' && (self.parent.parent.name[0..3]+'_')) || '')
    nam    = self.name.split(' ')[0..1].join('_')
    hdl = "\##{self.flavor_letter}_#{gran_nm[0..4]}#{par_nm[0..4]}#{nam}".downcase.gsub(/[()\.:\/\\]/,'')
    need_sfx = (Structure.where(handle:hdl).any?) && (self.handle!=hdl)
    hdl + ((need_sfx) ? SecureRandom.alphanumeric : '')
  end

  def build_handle()
    self.handle = self.gen_handle() unless self.handle.present?
  end

  #
  # ENUMS
  #

  enum flavor: [:condition, :action, :condition_group, :risk]

end

app/controllers/admin/structures_controller.rb
class Admin::StructuresController < AdminController
  before_action :set_structure, only: [:show, :edit, :update, :destroy]

  def index
    @structures = Structure.all
  end

  def show
  end

  def new
    @structure = Structure.new
  end

  def edit
  end


  # TODO
  # Add Order
  def create
    @structure = Structure.new(structure_params)

    respond_to do |format|
      if @structure.save
        format.html { redirect_to [:admin, @structure], notice: 'Structure was successfully created.' }
        format.json { render :show, status: :created, location: @structure }
      else
        format.html { render :new }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      res = @structure.update(structure_params())
      if res
        format.html { redirect_to [:admin, @structure], notice: 'Structure was successfully updated.' }
        format.json { render :show, status: :ok, location: @structure }
      else
        format.html { render :edit }
        format.json { render json: @structure.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @structure.destroy
    respond_to do |format|
      format.html { redirect_to tree_admin_structures_url, notice: 'Structure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_structure
    @structure = Structure.find(params[:id])
  end

  def structure_params
    params.require(:structure).permit(
      :name,
      :flavor,
      :key,
      :data,
      :parent_id,
      :text,
      :picker,
      :handle,
      :impacts,
      :ordering,
      :active
    )
  end

end

app/controllers/api/structures_controller.rb
class Api::StructuresController < ApiController
  def conditions
    @structures = Structure.condition.roots
    @flavor = "condition"
    render :index
  end

  def actions
    @structures = Structure.find(Structure.action.pluck(Arel.sql("DISTINCT parent_id")))
    @flavor = "action"
    render :index
  end
end

app/views/admin/structures/_form.html.haml
= form_for [:admin, @structure], html: {style: 'display:inline', role: 'form'} do |f|
  - if @structure.errors.any?
    #error_explanation
      %h2= "#{pluralize(@structure.errors.count, "error")} prohibited this structure from being saved:"
      %ul
        - @structure.errors.full_messages.each do |message|
          %li= message
  = f.submit 'Save', class: "btn btn-primary mr-2"
  %br
  %br
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :flavor
    = select_tag "structure[flavor]", options_for_select(Structure.flavors.keys, @structure.flavor), { class: 'form-control' }
  .form-group
    = f.label :handle
    = f.text_field :handle, class: 'form-control'
  .form-group
    = f.label :data
    -# = f.text_area :data, class: 'form-control', style: 'font-family:monospace;'
    = react_component('admin/JsonEditPane', {data:@structure.data, id:'structure_data', name:'structure[data]', width:'100%', style:{display:'noXXXXne'}} )
  .form-group
    = f.label :text
    = f.text_area :text, class: 'form-control', style: 'font-size:18px; font-family:monospace; height:100px; background:black; color:yellow;'
  .form-group
    = f.label :picker
    = f.text_field :picker, class: 'form-control'
  .form-group
    = f.label :impacts
    = f.text_area :impacts, class: 'form-control', style: 'font-size:18px; font-family:monospace; height:500px; background:black; color:#4EE077;'
  .border.border-dark.p-3.mb-4
    .form-group
      = f.label :parent
      = f.select :parent_id, nested_set_options(Structure, @structure) {|i| "#{'-' * i.level} #{i.name}" }, {include_blank: true}, { class: 'form-control' }
    %p
      %b Siblings:
      - if @structure.parent && @structure.parent.children.try(:any?)
        \|
        - @structure.parent.children.each do |child|
          - if @structure.id == child.id
            &gt;&gt;&gt;
          = "#{child.ordering}."
          = child.name
          \|

    .form-group
      = f.label :ordering
      = f.text_field :ordering, class: 'form-control'

    .form-group
      = f.label :active
      = f.check_box :active
      
  .actions.d-inline
    = f.submit 'Save', class: "btn btn-primary mr-2"

app/views/admin/structures/_tree_node.html.haml
%li.list-group-item{class: node.flavor.parameterize}
  %span{style:'color:#999;font-size:0.8rem'}
    = (node.flavor=='condition_group') ? 'Group' : node.flavor.try(:capitalize)
  %small.pb-2{style:'color:#999'}
    - if ( !node.picker.empty? )
      %span.pl-4{style:'color:#ccc'}
        Picker:
      %code{style:'color:#999'}
        = node.picker
    - if ( node.data_hash && (node.data != '{}') )
      %span.pl-4{style:'color:#ccc'}
        data:
      %span= "{ #{ safe_top_keys(node.data_hash) } }"
      - if (!node.active)
        %span.ml-4{style:'color:#744'} Inactive
    %span{style:'float:right;'}= node.handle
    %br
    = node.ordering && "#{node.ordering}."
    = link_to node.name, [:admin, node], style:'text-decoration:underline; color:#58b; font-size:120%'
    = link_to 'Edit', edit_admin_structure_path(node), class: ('btn btn-sm btn-light ml-1'), style: 'height: 1.4rem; line-height:0.8; color:grey; border:solid 1px #eee'
  - if node.children.try(:any?)
    %ul.list-group.pt-2
      - node.children.sort_by{|n| (n['ordering'] || 10000)}.each do |child|
        = render partial: "tree_node", locals: {node: child}

app/views/admin/structures/edit.html.haml
%h1 Editing structure

= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'Show', [:admin, @structure], class: 'btn btn-secondary mr-2'

= render 'form'

= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'Show', [:admin, @structure], class: 'btn btn-secondary mr-2'

app/views/admin/structures/index.html.haml
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'New Structure', new_admin_structure_path, class:'btn btn-secondary mr-2'
%br
%br
%table.datatables{'data-page-length':'25'}
  %thead
    %tr
      %th Name
      %th Flavor
      %th Parent
      %th Text
      %th Picker
      %th Data
      %th

  %tbody
    - @structures.each do |structure|
      %tr
        %td= structure.name
        %td= structure.flavor
        %td= structure.parent.try(:name)
        %td= truncate structure.text
        %td
          %code{style:'font-size:7px'}
            = structure.picker && structure.picker[0..15] + ((structure.picker.length>15) ? '...' : '')
        %td= ( structure.data && safe_top_keys(structure.data_hash) ) || ''
        %td
          = link_to 'Show', [:admin, structure]
          = link_to 'Edit', edit_admin_structure_path(structure)
          = link_to 'Destroy', [:admin, structure], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'New Structure', new_admin_structure_path, class:'btn btn-secondary mr-2'

app/views/admin/structures/new.html.haml
%h1 New structure

= link_to 'Back', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'

= render 'form'

= link_to 'Back', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'

app/views/admin/structures/show.html.haml
%p#notice= notice

= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'Edit', edit_admin_structure_path(@structure), class:'btn btn-primary mr-2'
= link_to 'New', new_admin_structure_path, class:'btn btn-secondary mr-2'

%br
%br

%p
  %b.d-inline Name:
  %b{style:'font-size:30px'}
    = @structure.name
%p
  %b Handle:
  = @structure.handle
%p
  %b Flavor:
  = @structure.flavor
%p
  %b Text:
  %pre.codified{style:'background:#222; color:yellow; padding:30px;'}
    = @structure.text
%p
  %b Picker:
  %code= @structure.picker
%p
  %b Data:
  %pre.codified{style:'background:#222; color:lime; padding:30px;'}
    = JSON.pretty_generate(@structure.data, {indent: "  ", object_nl: "\n"})
%p
  %b Impacts:
  %pre.codified{style:'background:#222; color:lime; padding:30px;'}
    = @structure.impacts
.border.border-dark.p-3.mb-4
  %p
    %b Parent:
    - if @structure.parent
      = link_to @structure.parent.try(:name), [:admin, @structure.parent]
    -# = @structure.parent.try(:name)
  %p
    %b Children:
    - if @structure.children.try(:any?)
      \|
      - @structure.children.each do |child|
        = "#{child.ordering}."
        = link_to child.name, [:admin, child]
        \|
  %p
    %b Siblings:
    - if @structure.parent && @structure.parent.children.try(:any?)
      \|
      - @structure.parent.children.each do |child|
        - if @structure.id == child.id
          &gt;&gt;&gt;
        = "#{child.ordering}."
        = link_to child.name, [:admin, child]
        \|
  %p
    %b Ordering:
    = @structure.ordering
  %p
    %b Active:
    = @structure.active

= link_to '< Table', admin_structures_path, class:'btn btn-secondary mr-2'
= link_to '< Tree', tree_admin_structures_path, class:'btn btn-secondary mr-2'
= link_to 'Edit', edit_admin_structure_path(@structure), class:'btn btn-primary mr-2'
= link_to 'New', new_admin_structure_path, class:'btn btn-secondary mr-2'
= link_to 'Destroy', [:admin, @structure], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-secondary text-danger mr-2'

app/views/admin/structures/tree.html.haml
= link_to "< Table", admin_structures_path, class:'btn btn-secondary' 
= link_to 'New Structure', new_admin_structure_path, class:'btn btn-secondary mr-2'
%br
%br

%ul.list-group.metric__tree
  - Structure.roots.sort_by{|n| (n['ordering'] || 10000)}.each do |root|
    = render partial: "tree_node", locals: {node: root}

%br
= link_to "< Table", admin_structures_path, class:'btn btn-secondary'
= link_to 'New Structure', new_admin_structure_path, class:'btn btn-secondary mr-2'