config/routes.rb
Rails.application.routes.draw do

  #
  # API
  #

  namespace :api, defaults: { format: :json } do
    get 'status' => 'status#index'

    scope ':key' do
      get 'status' => 'status#index'

      resources :journeys, only: [:create, :update, :destroy]

      get 'conditions' => 'structures#conditions'
      get 'actions'    => 'structures#actions'
      get 'all'        => 'structures#all'
    end
  end

  #
  # Admin
  #

  namespace :admin do
    get '', to: 'home#index', as: :home

    resources :api_keys
    resources :journeys
    resources :structures do
      get :tree, on: :collection
    end
    resources :users
  end

  #
  # Devise
  #

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
  end

  #
  # Application
  #
  get 'j/:token',   to: 'home#share',  as: :share
  get 'conditions', to: 'home#conditions', as: :conditions
  get 'actions',    to: 'home#actions', as: :actions
  get 'save',       to: 'home#save', as: :save
  get 'journeys',   to: 'home#journeys', as: :journeys
  get 'raw',        to: 'home#raw', as: :raw

  resources :journeys, only: [:index, :show, :destroy]

  #
  # Defaults
  #

  root to: "home#index"
end

app/models/api_key.rb
class ApiKey < ApplicationRecord

  #
  # Validations
  #

  validates :key, presence: true
  validates :secret, presence: true, uniqueness: { scope: :key }

  #
  # Associations
  #

  belongs_to :user, optional: true

  #
  # Scopes
  #

  scope :active, ->{ where(active: true) }

  #
  # Generators
  #

  after_initialize :check_key_and_secret

  def check_key_and_secret
    unless key.present? && secret.present?
      self.key = SecureRandom.uuid
      self.secret = SecureRandom.hex
    end
  end

  #
  # Finders
  #

  def self.tanjo_admin
    ApiKey.joins(:user).where("users.email" => "admin@tanjo.ai").first
  end

end

app/controllers/admin/api_keys_controller.rb
class Admin::ApiKeysController < AdminController
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]

  # GET /admin/api_keys
  # GET /admin/api_keys.json
  def index
    @api_keys = ApiKey.includes(:user)
  end

  # GET /admin/api_keys/1
  # GET /admin/api_keys/1.json
  def show
  end

  # GET /admin/api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /admin/api_keys/1/edit
  def edit
  end

  # POST /admin/api_keys
  # POST /admin/api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to [:admin, @api_key], notice: 'Api key was successfully created.' }
        format.json { render :show, status: :created, location: @api_key }
      else
        format.html { render :new }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/api_keys/1
  # PATCH/PUT /admin/api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to [:admin, @api_key], notice: 'Api key was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_key }
      else
        format.html { render :edit }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/api_keys/1
  # DELETE /admin/api_keys/1.json
  def destroy
    @api_key.update(active: false)
    respond_to do |format|
      format.html { redirect_to admin_api_keys_url, notice: 'Api key was successfully deactivated.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_key
      @api_key = ApiKey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_key_params
      params.require(:api_key).permit(:user_id, :key, :secret, :active)
    end
end

app/views/admin/api_keys/_form.html.haml
= form_for [:admin, @api_key] do |f|
  - if @api_key.errors.any?
    #error_explanation
      %h2= "#{pluralize(@api_key.errors.count, "error")} prohibited this api_key from being saved:"
      %ul
        - @api_key.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :user_id
    = f.collection_select :user_id, User.order(:email), :id, :email, {include_blank: true}, { class: 'form-control' }
  .form-group
    = f.label :active
    = f.check_box :active
  .form-group
    = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/api_keys/edit.html.haml
= render 'form'

= link_to 'Show', [:admin, @api_key]
\|
= link_to 'Back', admin_api_keys_url

app/views/admin/api_keys/index.html.haml
%table.datatables
  %thead
    %tr
      %th User
      %th Key
      %th Active
      %th Actions

  %tbody
    - @api_keys.each do |api_key|
      %tr
        %td
          - if api_key.user
            = link_to api_key.user.email, [:admin, api_key.user]
        %td= link_to api_key.key, [:admin, api_key]
        %td= api_key.active
        %td
          = link_to 'Show', [:admin, api_key]
          = link_to 'Edit', edit_admin_api_key_path(api_key)
          = link_to 'Deactivate', [:admin, api_key], method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Api key', new_admin_api_key_path

app/views/admin/api_keys/new.html.haml
= render 'form'

= link_to 'Back', admin_api_keys_url

app/views/admin/api_keys/show.html.haml
%p
  %b User:
  = link_to @api_key.user.email, [:admin, @api_key.user]
%p
  %b Key:
  = @api_key.key
%p
  %b Secret:
  = @api_key.secret
%p
  %b Active:
  = @api_key.active

= link_to 'Edit', edit_admin_api_key_path(@api_key)
\|
= link_to 'Back', admin_api_keys_url