config/routes.rb
Rails.application.routes.draw do

  #
  # API
  #

  namespace :api, defaults: { format: :json } do
    get 'status' => 'status#index'

    scope ':key' do
      get 'status' => 'status#index'

      resources :journeys, only: [:create, :update, :destroy]

      get 'conditions' => 'structures#conditions'
      get 'actions'    => 'structures#actions'
      get 'all'        => 'structures#all'
    end
  end

  #
  # Admin
  #

  namespace :admin do
    get '', to: 'home#index', as: :home

    resources :api_keys
    resources :journeys
    resources :structures do
      get :tree, on: :collection
    end
    resources :users
  end

  #
  # Devise
  #

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
  end

  #
  # Application
  #
  get 'j/:token',   to: 'home#share',  as: :share
  get 'conditions', to: 'home#conditions', as: :conditions
  get 'actions',    to: 'home#actions', as: :actions
  get 'save',       to: 'home#save', as: :save
  get 'journeys',   to: 'home#journeys', as: :journeys
  get 'raw',        to: 'home#raw', as: :raw

  resources :journeys, only: [:index, :show, :destroy]

  #
  # Defaults
  #

  root to: "home#index"
end

app/views/layouts/_admin_navbar.html.haml
%nav.navbar.navbar-expand-md
  = link_to logo_image, root_path, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon= fa_icon "bars", style: "color: white"
  #navbarCollapse.collapse.navbar-collapse
    .navbar-nav.mx-auto

    %ul.navbar-nav
      - if current_user
        - if current_user.is_admin
          %li.nav-item= link_to "Admin", admin_home_path, class: "nav-link"
        %li.nav-item.dropdown
          %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = current_user.display_name
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
            = link_to "Manage My Account", edit_user_registration_path, class: "dropdown-item"
            = link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: "delete"
      - else
        %li.nav-item= link_to "Sign In", new_user_session_path, class: "nav-link"
        %li.nav-item= link_to "Sign Up", new_user_registration_path, class: "nav-link"

app/views/layouts/_analytics.html.haml
%script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=#{ENV['GOOGLE_ANALYTICS_ID']}"}
:javascript
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '#{ENV['GOOGLE_ANALYTICS_ID']}');

app/views/layouts/_flash.html.haml
- if flash
  - flash.to_h.each do |key, value|
    - next if key.to_s == 'timedout'
    .cc-alert.alert.text-center.alert-dismissible.fade.show{class: flash_class(key), role: :alert}
      = value
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×

app/views/layouts/_meta.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:content => "minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, width=device-width", :name => "viewport"}/
%title= meta_title
= csrf_meta_tags
= csp_meta_tag
= stylesheet_pack_tag 'application', media: 'all'
= javascript_pack_tag 'application'
= stylesheet_link_tag 'https://3dbiome.s3.amazonaws.com/TemplateData/UnityStyle.css', media: 'all'
= yield :header_scripts

app/views/layouts/_navbar_link.html.haml
.cc-sidebar__nav.position-relative{class: ["cc-sidebar__nav--#{location}", active_state(location)]}
  = link_to link, class: "nav-link" do
    = icon(icon)
    - if active_state?(location)
      %span.sr-only (current)
    - if subtext
      .cc-sidebar__nav--subtext= subtext

app/views/layouts/admin.html.haml
!!!
%html.h-100
  %head
    = render "layouts/meta"
    = stylesheet_link_tag '//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css'
    = stylesheet_link_tag '//cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css'
    = javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js'
    = javascript_include_tag 'https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js'
    = javascript_include_tag 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
    :javascript
      $(document).ready(function(){
        $('table.datatables').DataTable();
        $('select').select2();
      });
  %body.admin.h-100
    = render "layouts/admin_navbar"
    .container-fluid.admin-container{style:'background:white; padding-bottom: 40px'}
      .row
        %nav#sidebarMenu.col-md-3.col-lg-2.d-md-block.bg-light.sidebar.collapse
          .sidebar-sticky.pt-3
            %ul.nav.flex-column.admin-nav
              %li.nav-item= link_to("Home", "/admin", class: admin_link_classes("home"))
              - admin_cms_options.each do |link, text|
                %li.nav-item= link_to(text.titleize, "/admin/#{link}", class: admin_link_classes(text))
        %main.col-md-9.ml-sm-auto.col-lg-10.px-md-4{:role => "main"}
          = render "layouts/flash"
          .d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pt-3.pb-2.mb-3.border-bottom
            %h1.h2 #{@scope} #{controller_name.titleize}
          = yield

    = render "layouts/analytics"

app/views/layouts/application.html.haml
!!!
%html.h-100
  %head
    = render "layouts/meta"
  %body.h-100
    .container-fluid.h-100.px-0
      .cc.row.m-0.h-100
        -# %nav.cc-leftcol.cc-leftcol__top.d-none.d-md-block.col-12.col-md-1.p-0
          -# = render partial: "layouts/navbar_link", locals: {location: :settings, icon: "Settings", link: "#", subtext: ""}

        %nav.navbar.navbar-expand-md.cc-maincol.cc-navbar.navbar.shadow.bg-white
          = link_to logo_image, root_path, class: "navbar-brand ml-3"
          %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon= fa_icon "bars", style: "color: white"
          #navbarCollapse.collapse.navbar-collapse
            .navbar-nav.mx-auto

            %ul.navbar-nav
              - if current_user
                - if current_user.is_admin
                  %li.nav-item= link_to "Admin", admin_home_path, class: "nav-link"
                %li.nav-item.dropdown
                  %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    Hi, #{current_user.display_name}
                  .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
                    - if current_user.is_admin
                      = link_to "Admin", admin_home_path, class: "dropdown-item"
                    = link_to "Manage My Account", edit_user_registration_path, class: "dropdown-item"
                    = link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: "delete"
              - else
                %li.nav-item= link_to "Sign In", new_user_session_path, class: "nav-link"
                %li.nav-item= link_to "Sign Up", new_user_registration_path, class: "nav-link"

        -# %nav.cc-leftcol.cc-nav.col-12.col-md-1.p-0
        -#   = render partial: "layouts/navbar_link", locals: {location: :conditions,      icon: "Settings",      link: conditions_path,      subtext: "Conditions"}
        -#   = render partial: "layouts/navbar_link", locals: {location: :actions,         icon: "RiskSimulator", link: actions_path,         subtext: "Healthy Actions"}
        -#   = render partial: "layouts/navbar_link", locals: {location: :save_journey,    icon: "Arrow_White",   link: journeys_path,        subtext: "Save Journey"}
        -#   = render partial: "layouts/navbar_link", locals: {location: :journeys,        icon: "Hamburger",     link: journeys_path,        subtext: "Health Journeys"}

        %main.cc-maincol.cc-main.box.p-0{role: "main"}
          = render "layouts/flash"
          -# - if @title
          -#   .row.p-3
          -#     .col-12
          -#       %h1= @title
          = yield
          - unless @location == :map
            .powered-by-tanjo.hidden-print
              = link_to image_tag("logos/tanjo.png", alt: "Tanjo.ai Machine Learning"), "https://tanjo.net", target: "_blank"

    = render "layouts/analytics"